global:
  scrape_interval: 15s
  evaluation_interval: 15s

# TODO(rradziukiewicz) Add Alert Manager and rules for calculating metrics.

scrape_configs:
  - job_name: go-app
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: [localhost:9090]
