global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: example-go-server
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets: [localhost:8080]
